### ISSUE TITLE
Temporary Discord channel for Discussion Related to This Repo?

### ISSUE THREAD

**Issue by timmhuang** [WSB-research/Wall-Street-Bets-Master-Doc#1]
I know we have a WSB Discord server, but I feel this Git repository deserves its own channel on that server. Or another different comm. platform such as Slack.

**Comment by tendiequest** [comment]
It would make it a lot easier.

**Comment by tshallenberger** [comment]
There's a github channel I've been posting helpful information and working with people new to Git.
